-- Supabase Schema for Pump Manager (Dynamic Product-Wise Normalization)

-- ==========================================
-- 1. CLEANUP & INITIAL SETUP
-- ==========================================
DO $$
DECLARE
    r RECORD;
BEGIN
    -- Drop old redundant/plural table names
    EXECUTE 'DROP TABLE IF EXISTS credits CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS expenses CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS recoveries CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS credit_entries CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS expense_entries CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS recovery_entries CASCADE';

    -- Drop other legacy tables
    EXECUTE 'DROP TABLE IF EXISTS nozzle_readings CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS ms_nozzle_readings CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS hsd_nozzle_readings CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS general_nozzle_readings CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS audit_line_items CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS daily_configs CASCADE';
    EXECUTE 'DROP TABLE IF EXISTS connection_test CASCADE';

    -- Drop dynamic nozzle tables (if any)
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'readings_%') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
    END LOOP;
END $$;

-- ==========================================
-- 2. SCHEMA-LEVEL PERMISSIONS
-- ==========================================
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;

-- ==========================================
-- 3. CORE TABLES (USEFUL)
-- ==========================================

CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    mobile_number TEXT UNIQUE NOT NULL,
    username TEXT,
    owner_name TEXT,
    pump_name TEXT,
    role TEXT DEFAULT 'STAFF',
    password_hash TEXT,
    created_at BIGINT DEFAULT extract(epoch from now()) * 1000,
    updated_at BIGINT DEFAULT extract(epoch from now()) * 1000
);

CREATE TABLE IF NOT EXISTS memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_phone TEXT NOT NULL,
    admin_phone TEXT NOT NULL,
    pump_name TEXT,
    username TEXT,
    role TEXT,
    account_id UUID,
    created_at BIGINT DEFAULT extract(epoch from now()) * 1000,
    UNIQUE(staff_phone, admin_phone)
);

CREATE TABLE IF NOT EXISTS pumps (
    mobile_number TEXT PRIMARY KEY,
    pump_name TEXT NOT NULL,
    num_ms_nozzles INTEGER DEFAULT 0,
    ms_nozzle_labels TEXT,
    num_hsd_nozzles INTEGER DEFAULT 0,
    hsd_nozzle_labels TEXT,
    num_ms_tanks INTEGER DEFAULT 0,
    num_hsd_tanks INTEGER DEFAULT 0,
    ms_tank_labels TEXT,
    hsd_tank_labels TEXT,
    product_names TEXT,
    udhari_names TEXT,
    updated_at BIGINT DEFAULT extract(epoch from now()) * 1000
);

CREATE TABLE IF NOT EXISTS staff_members (
    phone TEXT NOT NULL,
    owner_admin_phone TEXT NOT NULL,
    name TEXT,
    password_hash TEXT,
    role TEXT,
    account_id UUID,
    PRIMARY KEY (phone, owner_admin_phone)
);

CREATE TABLE IF NOT EXISTS registered_nozzles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_number TEXT NOT NULL,
    nozzle_type TEXT,
    label TEXT,
    nozzle_name TEXT,
    nozzle_number TEXT,
    nozzle_id TEXT,
    product_id TEXT,
    tank_name TEXT,
    tank_id TEXT,
    nozzle_index INTEGER,
    initial_reading DOUBLE PRECISION,
    is_active BOOLEAN DEFAULT TRUE,
    UNIQUE(mobile_number, label)
);

CREATE TABLE IF NOT EXISTS daily_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_phone TEXT NOT NULL,
    date TEXT NOT NULL,
    product_name TEXT NOT NULL,
    product_id TEXT,
    density DOUBLE PRECISION,
    rate DOUBLE PRECISION,
    opening_stock DOUBLE PRECISION,
    entered_by TEXT,
    timestamp BIGINT DEFAULT extract(epoch from now()) * 1000,
    UNIQUE(admin_phone, date, product_name)
);

CREATE TABLE IF NOT EXISTS saved_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_admin_phone TEXT NOT NULL,
    date TEXT NOT NULL,
    ca_name TEXT,
    meter_no TEXT,
    audit_type TEXT,
    summary_text TEXT,
    html_content TEXT,
    timestamp BIGINT,
    cash_submitted DOUBLE PRECISION,
    actual_cash_collected DOUBLE PRECISION,
    report_id TEXT,
    total_fuel_sales_amount DOUBLE PRECISION,
    total_udhari_jama DOUBLE PRECISION,
    total_kharch DOUBLE PRECISION,
    total_udhar DOUBLE PRECISION,
    phone_pe_amount DOUBLE PRECISION,
    cards_amount DOUBLE PRECISION,
    expected_cash_balance DOUBLE PRECISION,
    tally_difference DOUBLE PRECISION
);

-- ==========================================
-- 4. SPECIALIZED FINANCIAL TABLES
-- ==========================================

CREATE TABLE IF NOT EXISTS udhari (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id TEXT NOT NULL,
    owner_admin_phone TEXT NOT NULL,
    party TEXT,
    description TEXT,
    amount DOUBLE PRECISION,
    date TEXT,
    timestamp BIGINT,
    ca_name TEXT,
    UNIQUE(report_id, timestamp, party, amount)
);

CREATE TABLE IF NOT EXISTS expense (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id TEXT NOT NULL,
    owner_admin_phone TEXT NOT NULL,
    description TEXT,
    category TEXT,
    amount DOUBLE PRECISION,
    date TEXT,
    timestamp BIGINT,
    ca_name TEXT,
    UNIQUE(report_id, timestamp, category, amount)
);

CREATE TABLE IF NOT EXISTS udhari_jama (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id TEXT NOT NULL,
    owner_admin_phone TEXT NOT NULL,
    party TEXT,
    description TEXT,
    amount DOUBLE PRECISION,
    date TEXT,
    timestamp BIGINT,
    ca_name TEXT,
    UNIQUE(report_id, timestamp, party, amount)
);

-- ==========================================
-- 5. ATOMIC REGISTRATION FUNCTION
-- ==========================================
DROP FUNCTION IF EXISTS register_new_owner_atomic(jsonb, jsonb, jsonb);

CREATE OR REPLACE FUNCTION register_new_owner_atomic(
    p_user_data JSONB,
    p_pump_data JSONB,
    p_nozzles JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_user_id UUID;
    v_mobile TEXT;
    v_nozzle JSONB;
    v_product_name TEXT;
    v_products TEXT[];
    v_table_name TEXT;
BEGIN
    v_mobile := p_user_data->>'mobile_number';

    -- 1. Upsert User
    INSERT INTO users (mobile_number, username, owner_name, pump_name, role, password_hash)
    VALUES (
        v_mobile,
        p_user_data->>'username',
        p_user_data->>'owner_name',
        p_user_data->>'pump_name',
        'ADMIN',
        p_user_data->>'password_hash'
    )
    ON CONFLICT (mobile_number)
    DO UPDATE SET
        username = EXCLUDED.username,
        owner_name = EXCLUDED.owner_name,
        pump_name = EXCLUDED.pump_name,
        password_hash = EXCLUDED.password_hash,
        updated_at = extract(epoch from now()) * 1000
    RETURNING id INTO v_user_id;

    -- 2. Upsert Pump Info
    INSERT INTO pumps (
        mobile_number, pump_name, num_ms_nozzles, ms_nozzle_labels,
        num_hsd_nozzles, hsd_nozzle_labels, num_ms_tanks, num_hsd_tanks,
        ms_tank_labels, hsd_tank_labels, product_names
    ) VALUES (
        v_mobile,
        p_pump_data->>'pump_name',
        (p_pump_data->>'num_ms_nozzles')::INTEGER,
        p_pump_data->>'ms_nozzle_labels',
        (p_pump_data->>'num_hsd_nozzles')::INTEGER,
        p_pump_data->>'hsd_nozzle_labels',
        (p_pump_data->>'num_ms_tanks')::INTEGER,
        (p_pump_data->>'num_hsd_tanks')::INTEGER,
        p_pump_data->>'ms_tank_labels',
        p_pump_data->>'hsd_tank_labels',
        p_pump_data->>'product_names'
    )
    ON CONFLICT (mobile_number) DO UPDATE SET
        pump_name = EXCLUDED.pump_name,
        num_ms_nozzles = EXCLUDED.num_ms_nozzles,
        ms_nozzle_labels = EXCLUDED.ms_nozzle_labels,
        num_hsd_nozzles = EXCLUDED.num_hsd_nozzles,
        hsd_nozzle_labels = EXCLUDED.hsd_nozzle_labels,
        num_ms_tanks = EXCLUDED.num_ms_tanks,
        num_hsd_tanks = EXCLUDED.num_hsd_tanks,
        ms_tank_labels = EXCLUDED.ms_tank_labels,
        hsd_tank_labels = EXCLUDED.hsd_tank_labels,
        product_names = EXCLUDED.product_names,
        updated_at = extract(epoch from now()) * 1000;

    -- 3. Upsert Membership
    INSERT INTO memberships (staff_phone, admin_phone, pump_name, username, role, account_id)
    VALUES (
        v_mobile,
        v_mobile,
        p_user_data->>'pump_name',
        p_user_data->>'owner_name',
        'ADMIN',
        v_user_id
    )
    ON CONFLICT (staff_phone, admin_phone) DO UPDATE SET
        pump_name = EXCLUDED.pump_name,
        username = EXCLUDED.username,
        account_id = EXCLUDED.account_id;

    -- 4. Delete and Re-insert Nozzles
    DELETE FROM registered_nozzles WHERE mobile_number = v_mobile;

    IF p_nozzles IS NOT NULL AND jsonb_array_length(p_nozzles) > 0 THEN
        FOR v_nozzle IN SELECT * FROM jsonb_array_elements(p_nozzles) LOOP
            INSERT INTO registered_nozzles (
                mobile_number, nozzle_type, label, nozzle_name, nozzle_number,
                nozzle_id, product_id, tank_name, tank_id, nozzle_index, initial_reading
            ) VALUES (
                v_mobile,
                v_nozzle->>'nozzle_type',
                v_nozzle->>'label',
                v_nozzle->>'nozzle_name',
                v_nozzle->>'nozzle_number',
                v_nozzle->>'nozzle_id',
                v_nozzle->>'product_id',
                v_nozzle->>'tank_name',
                v_nozzle->>'tank_id',
                (v_nozzle->>'nozzle_index')::INTEGER,
                (v_nozzle->>'initial_reading')::DOUBLE PRECISION
            );
        END LOOP;
    END IF;

    -- 5. DYNAMICALLY CREATE PRODUCT READING TABLES
    v_products := string_to_array(p_pump_data->>'product_names', ',');

    FOREACH v_product_name IN ARRAY v_products LOOP
        -- Standardize table names: Petrol, Diesel, Premium
        v_table_name := lower(trim(v_product_name));
        IF v_table_name IN ('ms', 'petrol', 'motor spirit', 'ms petrol') THEN
            v_table_name := 'petrol';
        ELSIF v_table_name IN ('hsd', 'diesel', 'high speed diesel', 'hsd diesel') THEN
            v_table_name := 'diesel';
        ELSIF v_table_name LIKE '%premium%' OR v_table_name LIKE '%speed%' OR v_table_name LIKE '%power%' THEN
            v_table_name := 'premium';
        ELSE
            v_table_name := lower(replace(trim(v_product_name), ' ', '_'));
        END IF;

        v_table_name := v_table_name || '_readings';

        EXECUTE format('
            CREATE TABLE IF NOT EXISTS %I (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                report_id TEXT NOT NULL,
                owner_admin_phone TEXT NOT NULL,
                product_name TEXT NOT NULL,
                date TEXT NOT NULL,
                ca_name TEXT,
                timestamp BIGINT,
                nozzle_label TEXT NOT NULL,
                opening DOUBLE PRECISION,
                closing DOUBLE PRECISION,
                testing DOUBLE PRECISION,
                net_sales DOUBLE PRECISION,
                UNIQUE(report_id, nozzle_label)
            )', v_table_name);

        EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', v_table_name);
        EXECUTE format('GRANT ALL ON TABLE %I TO anon, authenticated, service_role', v_table_name);
    END LOOP;

    RETURN jsonb_build_object(
        'id', v_user_id,
        'mobile_number', v_mobile,
        'username', p_user_data->>'username',
        'pump_name', p_user_data->>'pump_name'
    );
END;
$$;

-- ==========================================
-- 6. FINAL PERMISSION GRANTS
-- ==========================================
GRANT EXECUTE ON FUNCTION register_new_owner_atomic(jsonb, jsonb, jsonb) TO anon, authenticated, service_role;

DO $$
DECLARE
    t RECORD;
BEGIN
    FOR t IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'ALTER TABLE ' || quote_ident(t.tablename) || ' DISABLE ROW LEVEL SECURITY';
        EXECUTE 'GRANT ALL ON TABLE ' || quote_ident(t.tablename) || ' TO anon, authenticated, service_role';
    END LOOP;
END $$;
